### ISSUE TITLE
Error with VERIFY_SERVICE_SID

### ISSUE THREAD

**Issue by nirenj** [robinske/serverless-phone-verification#1]
I am getting below error after I follow exactly the same as per your files. Kindly advise if any extra steps required. Thanks.

{
    "success": false,
    "message": {
        "status": 404,
        "message": "The requested resource /Services/VAxxxxxxxxxxxxxxxxx/Verifications was not found",
        "code": 20404,
        "moreInfo": "https://www.twilio.com/docs/errors/20404"
    }
}

**Comment by robinske** [comment]
Hey there - what was the API or function call that threw that error?

The only thing I can suggest without knowing more is that `VERIFY_SERVICE_SID` may not be set properly.

you can email me with more detail at krobinson@twilio.com

**Comment by MykytaPereverziev** [comment]
My pleasure to meet you. I have the same problem like @nirenj . Maybe you`ll help me. I think it is nonexistent sid (https://www.twilio.com/docs/api/errors/20404). I created more then three Verify/Services (took SERVICE ID and put in Function/Configure => +Key == SERVICE ID and VALUE some pass. Where my mistakes (my bug)? I can give screenshots or the same, connect Team Viewer. If better I can write you for email

**Comment by robinske** [comment]
I updated the project to use the Function APIs, the blog post is updated to match, it's much quicker to set up now!
